In [19]:
from agent import Agent
from referee.game import PlayerColor
agent = Agent(PlayerColor.RED)

agent

Testing: I am playing as red


In [2]:
action = agent.action()
action

SpawnAction(cell=HexPos(r=1, q=2))

In [3]:
from agent.board import MatrixBoard
import numpy as np

matrix = np.zeros([2,7,7], dtype=int)
board = MatrixBoard(matrix, 0, 0, 0)

In [4]:
from referee.game import \
    PlayerColor, Action, SpawnAction, SpreadAction, HexPos, HexDir

board.apply_action(SpawnAction(HexPos(1,1)), PlayerColor.RED)
board.apply_action(SpawnAction(HexPos(1,2)), PlayerColor.BLUE)
board.apply_action(SpreadAction(HexPos(1,1), HexDir.UpRight), PlayerColor.RED)

In [5]:
print(board.render(use_color=True, use_unicode=True))

                         ..     
                     ..      ..     
                 ..      ..      ..     
             ..      ..      ..      ..     
         ..      ..      ..      ..      ..     
     ..      r1      ..      ..      ..      ..     
 ..      ..      ..      ..      ..      ..      ..     
     ..      b1      ..      ..      ..      ..     
         ..      ..      ..      ..      ..     
             ..      ..      ..      ..     
                 ..      ..      ..     
                     ..      ..     
                         ..     



In [6]:
import math
from enum import Enum
from referee.game import \
    PlayerColor, Action, SpawnAction, SpreadAction, HexPos, HexDir
from agent.board import MatrixBoard

class MCState(Enum):
    UNVISITIED = 0;
    UNEXPANDED = 1;
    EXPANDED = 2;

class MCNode:
    def __init__(self, 
                 time_limit: float | None, 
                 space_limit: float | None,
                 board: MatrixBoard, 
                 color: PlayerColor,
                 action: Action = None,
                 parent = None,
                 ) -> None:
        self.playouts = 0
        self.wins = 0
        self.state = MCState.UNVISITIED
        self.time_limit = time_limit
        self.space_limit = space_limit
        self.board = board
        self.parent = parent
        self.children = []
        self.action = action
        self.color = color
        # self.ubc
    
    def is_over(self) -> bool:
        return self.board.game_over()
    
    def winner_color(self) -> PlayerColor | None: 
        return self.board.winner_color()
    
    def _ucb(self, c):
        '''
        Calculate the UCB score.
        '''
        return self.wins / self.playouts \
                + c * math.sqrt(2 * math.log(self.playouts) / self.playouts)

In [7]:
state_prev = np.zeros([2,7,7], dtype=int)
board_prev = MatrixBoard(state_prev, 0, 0, 0)
node_prev = MCNode(0, 0, board_prev, PlayerColor.RED, None, None)

node_curr = MCNode(0, 0, board_prev, PlayerColor.RED, None, None)

TypeError: MCNode.__init__() missing 4 required positional arguments: 'time_limit', 'space_limit', 'board', and 'color'

In [13]:
import numpy as np

# Create a NumPy array
# my_array = np.array([[1, 2, 3], [4, 5, 6]])
my_array = np.zeros([2,2,7,7], dtype=int).reshape([2, 2*7*7])

# Open the file in append mode
with open('my_file.csv', mode='w') as file:
    # Use np.savetxt() with the file object
    np.savetxt(file, my_array, delimiter=',')


In [14]:
# Read the CSV file as a float data type
my_array = np.loadtxt('my_file.csv', delimiter=',', dtype=float)
my_array.shape

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [16]:
my_array.reshape([2,2,7,7])

array([[[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0.,

In [17]:
my_array.shape

(2, 98)

In [18]:
def convert_action_to_array(action: Action) -> np.ndarray:
    match action:
        case SpawnAction(cell):
            return np.array([cell.r, cell.q, 0, 0])
            # pass
        case SpreadAction(cell, direction):
            return np.array([cell.r, cell.q, direction.r, direction.q])

In [24]:
convert_action_to_array(SpreadAction(HexPos(1,1), HexDir.Down)).reshape([1,-1]).shape

(1, 4)

In [29]:
i = 207
np.array([i], dtype=int).reshape(1, -1)

array([[207]])